version: '3.8'
services:
  mocha-node:
    container_name: mocha-node
    restart: always
    image: ghcr.io/celestiaorg/celestia-app:v2.2.0
    environment:
      POSTGRES_USER: test
    command:
      start --home /home --v2-upgrade-height 2585031
    volumes:
      - /mocha:/home
    ports:
      - 127.0.0.1:26857:26657
