---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  mickey:
    displayname: "Michael Zaikin"
    password: "$6$rounds=5000$aDFdsd32341sas5a$j5ApAf06V86Tt4zUp1CrtodWqOqiUfve7hOeLVMMoPl4Lk0hhNeq9qdUAoJTs4QZPaoj6htDYSltD/oURPGIm."
    email: mz@baking-bad.org
    groups:
      - admins
  artem:
    displayname: "Artem Poltorzhicky"
    password: "$6$rounds=5000$0123456789012345$bfsVm3MJ0c6UNjOWKWwNPrTV5EDvnk21NARGr4DEwxm3if/iWK6YkKsBaIo0pjTx.D4J8FC/zBgoTfufo0eeJ."
    email: ap@baking-bad.org
    groups:
      - admins
  miv:
    displayname: "Igor Matsak"
    password: "$6$rounds=5000$d4756j95uejkghnf$GSrirZdt7.nNC8QgXTugXSssvGMoGzyfr9xKgdOwjhIL8GQMP8uR3l3u9GQpRgIC1us4Ol3.HKMdUvQ2LTRWC."
    email: im@atomex.me
    groups:
      - admins
  okta:
    displayname: "Dmitry Mirgaleev"
    password: "$6$rounds=5000$Kbiqn49bmsajV923$zpjaCknCxlVMQa.5HjI.KKyOcRlDisFc3YB40.MiIRZbKIGRosXGlU5SUwWfKihKO89jljnvXr2tEtZWwqldj."
    email: dm@baking-bad.org
    groups:
      - admins
  droserasprout:
    displayname: "Lev Gorodetskiy"
    password: "$6$rounds=5000$fxF0jBAkUWUxnmSW$DfqkcXrT7ziS3QCVRP5oTE7hTNyHsUuNQT8Fjed4PM.HoaQAC0zW8u1DF7dOCzaE4Nzc6ja48lVpgd2c1jsjj1"
    email: lg@baking-bad.org
    groups:
      - admins
  max:
    displayname: "Max Strebkov"
    password: "$6$rounds=5000$saltsugarsaltsug$wq5NP2j0i8komGP7/sZ4kvL3qis88y19dvAtnbdPCJd1FkmYo/ZACHih4m3cZuZah9zb7sBm3nPUNopfJc2tN0"
    email: ms@baking-bad.org
    groups:
      - admins
  simaworks:
    displayname: "Sergey Simonyan"
    password: "$6$rounds=5000$oiuqwoiuqwelkqwn$a/jDi0GotCj2ZZ/hkQhImjrKD6Yg.sF.DS5MdmUEzV0jdp8PYnEr3sEEVa9FD6.YY9SWKNPOpRihkvntbbjIJ1"
    email: ss@baking-bad.org
  isereda:
    displayname: "Igor Sereda"
    password: "$6$rounds=5000$^hg4m?{N}nKap<u?$Y7vdsrC9D/BtaOqEOryr/tQxlf/BJhmfBVVK83ulHPXQuiGN.QpCincw5gt3oIB1R3S6wLRkHAx73VJeGBLXd/"
    email: is@baking-bad.org
  ztepler:
    displayname: "Stepan Naumov"
    password: "$6$rounds=5000$17f7a86d4b709263$cVwZRjNB2F4D14wZumbWIIlkIjcNivcZBhGNfubV9DjuXQdVb0aW3iMXIJgHF6bhTeiKXxq2u5JJlutA.Q4mJ."
    email: sn@baking-bad.org
  skubarenko:
    displayname: "Andrey Skubarenko"
    password: "$6$rounds=5000$tQNnDVHIVS9dr4#S$jDBZKHWD82NIW4wOa3aDvilTkn4JYwuslidLf8/lO/ZRgt3X07D4AJJnZKpauxlwLKJxT9V/vmqNvS2lRtlpR0"
    email: as@baking-bad.org
  lavysh:
    displayname: "Alexander Lavysh"
    password: "$6$rounds=5000$WhereItGonnaRand$aqZiLc4At8i4vRrHUjiLA3GlMTnrTloDJ3LqlDblncd2ar5bDhOcUoBhGd6Vy8.oxyMOo5hz3aDAAWeAy4ibW1"
    email: al@baking-bad.org
  gusev:
    displayname: "Petr Gusev"
    password: "$6$rounds=5000$hjkdsa123678yuer$EiEZkOeeMsLcSj1i.1vTDFq/HMcTl3N33BPOUADADAt4MLrb9zUgAp/7E1y6Il4xwE368G3nbg7VVCCSGfid20"
    email: pg@baking-bad.org
  maxima-net:
    displayname: "Maxim Kucherov"
    password: "$6$rounds=5000$abcdabcdabcdabcd$LAj5aFBQbMC075C9HUvMT.iy5qkvSNFyz8v38NiVdrpQ2fmt0yOKnpgZnitMKHp9uNj32MRjmxGvt99g12ki01"
    email: mk@baking-bad.org
  alexey:
    displayname: "Alexey Sivolapov"
    password: "$6$rounds=5000$Kbiqn49bmsajV923$zpjaCknCxlVMQa.5HjI.KKyOcRlDisFc3YB40.MiIRZbKIGRosXGlU5SUwWfKihKO89jljnvXr2tEtZWwqldj."
    email: siv@baking-bad.org
  vova:
    displayname: "Vladimir Zarechnev"
    password: "$6$rounds=5000$ax@ufH^3nJO09@db$ERitzFzREBTq6DRL7Qf4bRwL/17WEgnkfCusSF809hynAJQfO1aTAgeuPaRwVzpYrKZlHnEEWxmCSICG0m3vl0"
    email: tezosbakingbad@gmail.com
  zaariel:
    displayname: "Nikolay Aleshinkov"
    password: "$6$rounds=5000$ASDjkASDjklASFjl$10unjXUAAgSPBDv/IrwX9qOK9jPo/AheFYcj.ZGimsh45seaIwSED2rbquwiesj/KttZprgmhIJbT9OMzk72o/"
    email: na@baking-bad.org
  vbobrikov:
    displayname: "Vladimir Bobrikov"
    password: "$6$rounds=5000$p8nQLN0LWLP=TM+X$IrVzfG/GwleCh0vdpRP8qR3GxcXWfJJBCaIgaiFh1LSq66eE5RDcd3MjQm4LvumHIA1wJ6Ox.cfv42QsAAFpB0"
    email: vb@baking-bad.org