version: '3.8'
services:
  node:
    container_name: arabica-cons
    restart: always
    image: ghcr.io/celestiaorg/celestia-app:v3.0.0-arabica
    environment:
      POSTGRES_USER: test
    command:
      start --home /home --v2-upgrade-height 1751707
    volumes:
      - /arabica:/home
    ports:
      - 127.0.0.1:26657:26657
