version: '3.8'
services:
  mainnet-node:
    container_name: mainnet-node
    restart: always
    image: ghcr.io/celestiaorg/celestia-app:v3.0.2
    environment:
      POSTGRES_USER: test
    command:
      start --home /home --v2-upgrade-height 2371495
    volumes:
      - /mainnet:/home
    ports:
      - 127.0.0.1:26757:26657
